Show do Bilhão - Bia
COLTEC-DAW/E09-Show-do-Bilhao pull request #113
Opened 2023-08-10 23:02 UTC by beacms

2023-08-11 02:34 UTC, Bernardo-O-Silva commented
Boa noite! Primeiramente, queria falar que gostei bastante do código, a estilização está muito boa, as perguntas muito criativas e a funcionalidade é bastante - bem - funcional 😊

2023-08-11 02:37 UTC, Bernardo-O-Silva requested changes
No código do gameOver.php, o bloco HTML foi repetido 2 vezes no código, tome cuidado com isso 😢 
Ainda no mesmo código, acho que se adicionássemos um botão de Log Out aqui seria bastante interessante!

2023-09-01 20:04 UTC, jemaf commented
@beacms trabalho quase ok, não achei onde mantém exibido o score e data de último acesso

2023-09-01 20:06 UTC, jemaf commented
@Bernardo-O-Silva review ok 👍

2023-09-01 20:06 UTC, closed without merging

2023-09-01 21:24 UTC, beacms commented
Professor, se não me engano, estão no arquivo "mainarea.php"

Em sex., 1 de set. de 2023 17:04, João Eduardo Montandon <
***@***.***> escreveu:

> @beacms <https://github.com/beacms> trabalho quase ok, não achei onde
> mantém exibido o score e data de último acesso
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/COLTEC-DAW/E09-Show-do-Bilhao/pull/113#issuecomment-1703264804>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AY5ZC754OKXKY6OICIF5OHTXYI5WNANCNFSM6AAAAAA3ME7XKA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>